{% set version = "2.3.3" %}

package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9cf0f71d7a86ed0e08d417e97796ff22de43c60ce19dbaafa9b6b6169427fc40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps .


requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - libiconv
    - gdal =3.4.3
    - geopandas
    - jupyter
    - notebook
    - libpysal
    - pip
    - descartes
    - glpk
    - openpyxl
    - matplotlib
    - xlrd
    - pyomo
    - numpy
    - pandas
    - networkx
    - scipy
    - scikit-learn >=1.2
    - xarray
    - rasterio
    - netcdf4
    - tsam
    - sphinx
    - sphinx_rtd_theme
    - myst-parser
    - pytest <7.0
    - pytest-cov
    - nbval
    - black
    - pwlf
    - psutil
    - gurobi-logtools

test:
  imports:
    - fine
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
