{% set version = "2.2.3" %}

package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/v{{ version }}.tar.gz
  sha256: 38a7be8dd48d0addf65b1caee245c2a780d140bed4fafa4f253b802c1839346d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps .


requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-git
  run:
    - python  >=3.6
    - libiconv
    - gdal
    - geopandas
    - jupyter
    - notebook
    - libpysal
    - pip
    - descartes
    - glpk
    - openpyxl
    - matplotlib-base
    - xlrd
    - pyomo <6.4.2
    - numpy <=1.21
    - pandas <1.5
    - gpyopt
    - networkx
    - scipy
    - pwlf
    - pydoe
    - sphinx_rtd_theme
    - scikit-learn
    - xarray
    - statsmodels
    - seaborn
    - rasterio
    - netcdf4
    - pytest
    - pytest-cov
    - pylint
    - nbval
    - black
    - tsam
    - wquantiles
    - glpk

test:
  imports:
    - FINE
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
