{% set version = "2.3.1" %}

package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6191240AD67C4BB5F25698CBD3AD4A29A71892B6E8DDE045215AF2C02E241F82


build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps .


requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-git
  run:
    - python  >=3.6
    - libiconv
    - gdal 
    - geopandas
    - jupyter
    - notebook
    - libpysal
    - pip
    - descartes
    - glpk
    - openpyxl
    - matplotlib-base
    - xlrd 
    - pyomo <6.4.2
    - numpy <=1.21
    - pandas <1.5
    - gpyopt
    - networkx
    - scipy
    - pwlf
    - pydoe
    - sphinx_rtd_theme
    - scikit-learn
    - xarray
    - statsmodels
    - seaborn
    - rasterio
    - netcdf4
    - pytest
    - pytest-cov
    - pylint
    - nbval
    - black  
    - tsam
    - wquantiles
    - glpk
    - gurobi-logtools

test:
  imports:
    - FINE
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems. 
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
